# Default values for trippin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8080

resources: 
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 280Mi