global:
  env: local
  postgres:
    secret: postgres-credentials
    host: postgres-service
  redis:
    host: redis-service
  gcpApi:
    secret: gcp-api-credentials
postgres:
  volume: postgres-volume-mount
  db: kubernetes_django
  pvc: postgres-pvc