apiVersion: skaffold/v2alpha3
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: trippin
    context: .
    sync:
      infer:
      - 'base_app/*.py'
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      namespace: default
      #wait: true
      skipBuildDependencies: false 
      values:
        repository: trippin
        "global.repository": trippin
        "trippin.repository": trippin
  
