apiVersion: skaffold/v2alpha3
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: trippin/auth
    context: .
    sync:
      infer:
      - 'code/*'
deploy:
  helm:
    releases:
    - name: auth
      chartPath: ../charts/auth
      valuesFiles:
      - local-values.yaml  
      namespace: default
      skipBuildDependencies: false 
      values:
        "auth.image.repository": trippin/auth
      setValues:
        # "auth.image.repository": trippin/auth
        global.image.pullPolicy: Never
portForward:
- resourceType: deployment
  resourceName: auth-chart
  port: 8080
  localPort: 8080
