apiVersion: skaffold/v2alpha3
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: us.gcr.io/bubbly-delight-268221/github.com/trippin-developer-week/backend
    context: .
    sync:
      infer:
      - 'code/*'
deploy:
  helm:
    releases:
    - name: charts
      chartPath: charts
      namespace: default
      #wait: true
      skipBuildDependencies: false 
      values:
        "global.repository": us.gcr.io/bubbly-delight-268221/github.com/trippin-developer-week/backend
        "trippin.repository": us.gcr.io/bubbly-delight-268221/github.com/trippin-developer-week/backend
portForward:
- resourceType: deployment
  resourceName: charts-trippin
  port: 8080
  localPort: 8080
