# Default values for trippin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
global:
  env: prod
  repository: gcr.io/composite-keel-269505/trippin

resources: 
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 280Mi