apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
