# Generated by Django 2.2.4 on 2020-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the place', max_length=255, null=True)),
                ('address', models.TextField(help_text='The address associated with the place', null=True, unique=True)),
                ('place_id', models.CharField(help_text='The id associated with the place, this has to be unique', max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='The local phone number associated with the place', max_length=255, null=True)),
                ('price_level', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], help_text='The price level of the place', null=True)),
                ('rating', models.FloatField(blank=True, help_text='The aggregated rating of the place', null=True)),
                ('category_icon_url', models.TextField(blank=True, help_text='The icon url of the category related to this place', null=True)),
                ('google_maps_url', models.TextField(blank=True, help_text='The google maps url of the place', null=True)),
                ('website', models.TextField(blank=True, help_text='The website associated with the place', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_reference', models.CharField(help_text='The reference id associated with this photo', max_length=255, null=True)),
                ('height', models.IntegerField(help_text='The height associated with the image returned', null=True)),
                ('width', models.IntegerField(help_text='The width associated with the image returned', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='The name of the author associated with this review', max_length=255, null=True)),
                ('rating', models.IntegerField(help_text='The rating given by the author for the place', null=True)),
                ('text', models.TextField(blank=True, help_text="The user's review with respect to the place", null=True)),
                ('profile_photo_url', models.TextField(blank=True, help_text="The user's profile image url", null=True)),
            ],
        ),
    ]
