apiVersion: v1
kind: Service
metadata:
  name: flower-service
  labels:
    {{- include "flower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5555
      protocol: TCP
  selector:
    {{- include "flower.selectorLabels" . | nindent 4 }}
