apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
