kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ if eq .Values.global.env "local" }}
  volumeName: {{ include "postgres.fullname" . }}
{{ end }}