# Generated by Django 2.2.5 on 2020-02-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(editable=False, max_length=255, null=True)),
                ('dollar_sign', models.IntegerField(null=True)),
                ('title', models.CharField(editable=False, max_length=255, null=True)),
                ('location', models.CharField(editable=False, max_length=255, null=True)),
                ('latitude', models.CharField(editable=False, max_length=255, null=True)),
                ('longitude', models.CharField(editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255, null=True)),
                ('food_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='foodcard.FoodCard')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(editable=False, max_length=255, null=True)),
                ('username', models.CharField(editable=False, max_length=255, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('food_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='foodcard.FoodCard')),
            ],
        ),
    ]
