apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trippin-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /api/(.*)
        backend:
          serviceName: trippin
          servicePort: 8080
