apiVersion: v1
kind: Service
metadata:
  name: trippin
  labels:
    {{- include "trippin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
<<<<<<< HEAD
    {{- include "trippin.selectorLabels" . | nindent 4 }}
=======
    {{- include "framework.selectorLabels" . | nindent 4 }}
>>>>>>> be7c19e19bf1fb9cddb43346c3c12a64623f9f9c
