apiVersion: v1
kind: Service
metadata:
  name: trippin
  labels:
    {{- include "trippin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "trippin.selectorLabels" . | nindent 4 }}
