apiVersion: v1
kind: Service
metadata:
  name: framework
  labels:
    {{- include "framework.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "framework.selectorLabels" . | nindent 4 }}
