# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5555

requests:
  cpu: 100m
  memory: 100Mi  
limits:
  cpu: 100m
  memory: 128Mi

